name: Upload Go test results

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ '1.18.x', '1.19.x', '1.20.x' ]

        steps:
            - uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go-version }}
            - name: Install dependencies
              run: go get .
            - name: Test with Go
              run: go test -json > TestResults-${{ matrix.go-version }}.json
            - name: Upload Go test results
              uses: actions/upload-artifact@v3
              with:
                  name: Go-results-${{ matrix.go-version }}
                  path: TestResults-${{ matrix.go-version }}.json
